In [13]:
import numpy as np # لادراج مكتبة numpy 
import sys

In [ ]:
import sklearn  

In [14]:
a=np.array([1,2,3]) #a  و and array دالة المصفوفة
a

array([1, 2, 3])

In [7]:
b=np.array([[1,2,3],# لتكتابة مصفوفة  متعدد نستخدم [[]] للكتابة 
           [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#shape شكل المصفوقة
a.shape
b.shape

(2, 3)

In [9]:
#get dimension الابعاد
a.ndim
b.ndim

2

In [10]:
# data type نوع البيانات 
a.dtype
b.dtype

dtype('int32')

In [11]:
#array size حجم المصفوقة
a.itemsize
b.itemsize
a.size


3

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#تحديد عنصر محدد
b[0,1]

2

In [14]:
# طباعة صف كامل 
b[0,:]

array([1, 2, 3])

In [15]:
# طباعة عامود كامل 
b[:,0]

array([1, 4])

In [16]:
#تغير القيم
b[0,1]=21
    
b

array([[ 1, 21,  3],
       [ 4,  5,  6]])

In [17]:
# geting a littie more fancy[startidex:endindex:stapsize]
b[1:3]

array([[4, 5, 6]])

In [18]:
B=np.array([[1,2,3],# لتكتابة مصفوفة  متعدد نستخدم [[]] للكتابة 
           [4,5,6],
            [7,8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#تغير صف كامل
B[2:]=[9,8,7]
B

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [20]:
#ZERO array
np.zeros((2,2)) #ضع علامة قوسين في دالة و قوسين لحجم المصفوفات  



array([[0., 0.],
       [0., 0.]])

In [21]:
#one array
np.ones((2,2))

array([[1, 1],
       [1, 1]])

In [22]:
#المصفوف الاحاية
np.identity(3,dtype='int32') #كتابة الدلة داخلها قوسين و ضع رقم داخل القوسين  

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
#for ather number
np.full((2,2),45,dtype='int32')

array([[45, 45],
       [45, 45]])

In [46]:
#for ather number full_like 
np.full_like(a,4)
#التبديل القيم من مصفوفة محددة
np.full_like(C,[[7,7,3],
               [94,5,1]
                [9,7,3]])

NameError: name 'C' is not defined

In [0]:
#اقام عشوائية
#random number
np.random.rand(4,2)

In [0]:
# اقام عشوائية صحيحة
#random number int
np.random.randint(0,10, size=(2,2)) #عدد الارقام عشوائية التي تريد جلبهم وحجم المصفوفة

In [0]:
#لتكرارالمصفوفة
arr=np.array([[7,7,3],
               [4,5,1],
                [9,7,3]])

r1=np.repeat(arr,2,axis=0)
print(r1)

In [0]:
#دمج المصفوفات في مصفوفة واحد
output=np.ones((5,5),dtype='int32')
print(output)

z=np.zeros((3,3),dtype='int32')
print(z)

z[1,1]=9
z


output[1:-1,1:-1]=z
output

# Be careful when copying arrays

In [16]:
#نسخة من القيم 
#عند الاستبدال نسخ نفس القيم ولا تتبدل
# استخدام الدالة نسخ() لنسخ القيم بدون تكرار
 
x=np.array([1,2,3])
y=x.copy()
y[0]=100  
x


array([1, 2, 3])

# Math

In [0]:
x=np.array([1,2,3])
#جمع المصفوفات
x+2
#طرح المصفوفات
x-2
#ضرب المصفوفات
x*2
#قسمة المصفوفات
x/2 


In [0]:
#sin and cos and tan
np.sin(x)
np.cos(x)
np.tan(x)

# Liner algebra

In [15]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
#ضرب المصفوفات
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [0]:
#المحددة المصفوفة 
#find determinant
s=np.identity(3,dtype='int32')
np.linalg.det(s)

# Statistics

In [1]:
stat=np.array([[1,2,3],[4,5,6]])

#اصغر قيمة في المصوفة 
np.min(stat)
#اكبر قيمة في المصفوفة
np.max(stat)
#مجموع  قيمالمصفوفة
np.sum(stat)


NameError: name 'np' is not defined

# Reshaping

In [5]:
#stat=np.array([[1,2,3,4],[5,6,7,8]])
#print(stat.shape)# حجم المصفوفة

stat=np.array([[1,2,3,4],[5,6,7,8]])
print(stat.reshape((8,1))) #اعادة حجم المصفوفة

NameError: name 'np' is not defined

In [0]:
#دمج عاموي 
v1=np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.vstack([v1,v2])
              

In [0]:
#دمج افقي 
h1=np.array([1,2,3,4])
h2= np.array([5,6,7,8])
np.hstack([h1,v2])
              

# load data from file

In [1]:
#تنزيل البيانات من الملف 
filedata=np.genfromtxt("data.txt", delimiter=',')
filedata=filedata.astype('int32')
filedata


NameError: name 'np' is not defined

# Boolen masking

In [0]:
#شرط بعلامة صح او خط
filedata <50

In [0]:
#شروط استخدام القيم
(filedata <50)& (filedata <10) 

In [0]:
#تستخدم علام لنفي العبارة
[~(filedata <50)& (filedata <10)]

In [0]:
# استخدام الدالتان any and all
np.any(filedata >50)
np.all(filedata >50)

In [0]:
#شروط استخدام القيم
filedata [(filedata <50)& (filedata <10)]

In [0]:
#شرط استخدام القيم
filedata [(filedata <50)]

In [0]:
#تحدد عدد محدد من القيم 
stat=np.array([1,2,3,4,5,6,7,8])
stat
stat[[1,4,7]]

str

In [8]:
help(a)


NameError: name 'array' is not defined